production:
  adapter: mysql2
  database: chess
  pool: 5
  timeout: 5000
  encoding: utf8
  username: root
  password:

development:
  adapter: mysql2
  database: chess
  pool: 5
  timeout: 5000
  encoding: utf8
  username: root
  password:

test:
  adapter: mysql2
  database: chess_test
  pool: 5
  timeout: 5000
  encoding: utf8
  username: root
  password:

